###############################################################################
# storage.tf
# -----------------------------------------------------------------------------
# The workspace ROOT bucket (aka DBFS root / workspace storage). This is where
# Databricks stores workspace system data. It is NOT your Unity Catalog data
# bucket — that one is created in unity_catalog.tf.
#
# Security posture:
#   * Public access fully blocked.
#   * Server-side encryption (SSE-S3) on by default.
#   * Bucket policy generated by Databricks so the control plane can access it.
###############################################################################

resource "aws_s3_bucket" "root" {
  bucket        = "${local.name}-root"
  force_destroy = true # lets `terraform destroy` clean up non-empty buckets in a demo/starter.
  tags = merge(local.tags, {
    Name = "${local.name}-root"
  })
}

# Block ALL forms of public access — defense in depth.
resource "aws_s3_bucket_public_access_block" "root" {
  bucket                  = aws_s3_bucket.root.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "root" {
  bucket = aws_s3_bucket.root.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_versioning" "root" {
  bucket = aws_s3_bucket.root.id
  versioning_configuration {
    status = "Disabled"
  }
}

# Databricks generates the exact bucket policy the control plane requires.
data "databricks_aws_bucket_policy" "root" {
  provider = databricks.mws
  bucket   = aws_s3_bucket.root.bucket
}

resource "aws_s3_bucket_policy" "root" {
  bucket = aws_s3_bucket.root.id
  policy = data.databricks_aws_bucket_policy.root.json

  # Attach the policy only after public access is locked down.
  depends_on = [aws_s3_bucket_public_access_block.root]
}

# Register the bucket with the Databricks account as a "storage configuration".
resource "databricks_mws_storage_configurations" "this" {
  provider                   = databricks.mws
  account_id                 = var.databricks_account_id
  bucket_name                = aws_s3_bucket.root.bucket
  storage_configuration_name = "${local.name}-storage"
}
